services:
    base:
        profiles: ['build']
        build:
            context: .
            dockerfile: Dockerfile
            target: base
            args:
                PLATFORM: ${DOCKER_PLATFORM:-linux/arm64}

    merchant-site:
        profiles: ['build']
        build:
            context: .
            dockerfile: Dockerfile
            target: merchant-site
            network: host
            args:
                PLATFORM: ${DOCKER_PLATFORM:-linux/arm64}
                AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
                AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

    express:
        profiles: ['deploy']
        build:
            context: .
            dockerfile: Dockerfile
            target: express
            args:
                PLATFORM: ${DOCKER_PLATFORM:-linux/arm64}
        ports:
            - '8000:8000'

    mysql:
        profiles: ['dev']
        image: mysql:8.0
        restart: always
        ports:
            - '${MYSQL_PORT:-7102}:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE:-mydb}
            - MYSQL_USER=${MYSQL_USER:-myuser}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
