version: '3.8'

services:
    mysql:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '7000:3306'
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
