FROM postgres:16

# Any additional configurations can be added here
# For example:
# COPY ./init.sql /docker-entrypoint-initdb.d/

# The default PostgreSQL port
EXPOSE 5432

# You can set environment variables here if needed
# ENV POSTGRES_DB=mydb
# ENV POSTGRES_USER=myuser
# ENV POSTGRES_PASSWORD=mypassword
